### PR TITLE
Add worktree functionality: listing, add, remove and prune

### PR DESCRIPTION
**Pull request by hatkyinc2**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [X] Ensure all commits include DCO sign-off.
- [X] Ensure that your contributions pass unit testing.
- [X] Ensure that your contributions contain documentation if applicable.

### Description
Add worktree functionality: listing, add, remove and prune

fixes https://github.com/ruby-git/ruby-git/issues/477

### Checklist from feedback
- [x] Dedicated fixture for the worktree feature
- [X] README.md - Major Objects, add worktree
- [X] README.md - the big blob tree of read operations
- [X] README.md - the big blob tree of write operations
- [X] Squash commits

### CODE REVIEW

**Comment by jcouball** [comment]
@hatkyinc2 thank you for the PR.  The functionality looks good so far but before I study the functionality in depth, I'd get your feedback for two changes:

**What do you think about creating a test fixture specifically for this change?** Reusing the default test fixture (test/files/working/dot_git) as you can see breaks tests that don't have anything to do with the change you are making. To me this is tech debt that is piling up with each change like this one. The next PR might have to correct all the same tests plus the new ones introduced in this PR. Additionally, I think merge conflicts will be more of a problem if everyone is trying to change the same test fixture for their tests.

You can see an example of using a different fixture in `tests/units/test_diff_non_default_encoding.rb` for using the fixture `tests/files/encoding`

**Can you minimally document this new feature in the README.md?** There are two places this should be added.  In the MAJOR OBJECTS section and in EXAMPLES section.  Several examples will be helpful.  Note any caveats.

The CONTRIBUTING guide asks for YARD documentation, but I think there needs to be across the board rework / consistency to make that useful at this point.

**Comment by jcouball** [comment]
I re-ran the build and the status was updated.  Not sure why it wasn't updating before.

**Comment by hatkyinc2** [comment]
Glad to hear back, be happy to improve the patch.
So what I understand and am going to hack on:
* Dedicated fixture for the worktree feature
* README.md - Major Objects, add worktree
* README.md - the big blob tree of read operations
* README.md - the big blob tree of write operations

Was there other work I missed for now?

**Comment by hatkyinc2** [comment]
@jcouball Updated the patch according to above, dedicated fixture, not touching current tests, added docs.

**Comment by SolaWing** [comment]
@hatkyinc2 @jcouball  git diff in worktree is broken. report `index file open failed: Not a directory`. and debug, the GIT_INDEX_FILE environment is set to wrong path

**Pull request merged**
