### PR TITLE
Adds file option to config_set to allow adding to specific git-config files

### PR DESCRIPTION
**Pull request by codenamev**
### PR checklist
- [x] Review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.
- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description
There are many git configurations that are preferred to keep in a separate file to avoid committing sensitive information (in a global dotfile as an example).  This updates the `.config` method to accept a `file` option that allows you to specify the file to save the configuration to (this is equivalent to `git config --file some/custom/config name value`).

### CODE REVIEW

**Comment by codenamev** [comment]
@jcouball from the contributing docs it says to request a review from a maintainer.  I'm not entirely sure on the process for doing that (outside of pinging you directly like this).  If there is a preference of process I'd be happy to document it 😄 I'm unable to request a review via the typical GitHub UI.

**Comment by codenamev** [comment]
@perlun @tarcinil @jcouball Any interest in this feature?

**Comment by perlun** [comment]
> @perlun @tarcinil @jcouball Any interest in this feature?

Sorry for the lack of feedback. This project is rather unmaintained at the moment; @jcouball was the last one to review a merge request. James, would you have a chance to give this a look?

**Review by jcouball — APPROVED** [review]
Apologies for taking so long to get to this. This addition looks great!

The only thing it is missing is an entry in the README. I'll add this if I don't see a PR in the next day or two.

I'll plan on cutting a new minor-version release within the next week to get this in the gem.

**Pull request merged**
