### PR TITLE
Enable mirror option for git clone and push

### PR DESCRIPTION
**Pull request by guimaluf**
c.f. https://help.github.com/articles/duplicating-a-repository

Updating original PR #167 from
Author:    Lars Schneider <larsxschneider@gmail.com>
Date:      Sat Aug 9 23:24:41 2014 -0700

### CODE REVIEW

**Comment by kylemacey** [comment]
@guimaluf Are you planning on getting the tests passing so this could get merged in?

**Comment by kylemacey** [comment]
@guimaluf it looks like if you update your PR with the new commits in master from #344, it should fix up that JRuby test.

**Comment by tarcinil** [comment]
@kylemacey I actually had that issue as well, and already had #344 pulled in; I fixed it in #348 which is awaiting review.

**Comment by kylemacey** [comment]
@robertodecurnex @perlun @rvodden (Not sure exactly who to @-mention, just grabbing based off activity that I see) can we get a hand getting #348 and this PR over the finish line?

**Comment by kylemacey** [comment]
Another bump on this. Is this ok to merge?

**Comment by guimaluf** [comment]
If is needed I can rebase this... don't know what may be missing...

**Comment by dpmex4527** [comment]
Thanks @guimaluf! I don't see a lot of major changes since the last commit so test _should_ still pass.

**Comment by dpmex4527** [comment]
@guimaluf, @perlun thanks for merging this!!! @perlun will this PR be 🚢'ing in the 2.0 release? (I'm basing this Q on this issue comment: https://github.com/ruby-git/ruby-git/issues/341#issuecomment-362176147)

**Comment by perlun** [comment]
@dpmex4527 Either 1.3.1 or 1.4 I think, since it doesn't really break any B/C. I'm hoping we can publish it shortly - please ping the other thread and ask if @rvodden if he will do it or if he'll hand it off to someone else.

**Comment by dpmex4527** [comment]
@perlun sounds good! Thanks for helping get this feature shipped out :)

**Pull request merged**
