### PR TITLE
Refactor git config

### PR DESCRIPTION
**Pull request by mpapis**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description

The Git module has config and global_config methods that are available only when Git module is included. Refactored the code to remove duplication and to make it more explicit we are managing `git config` not the library setup.

### CODE REVIEW

**Comment by mpapis** [comment]
the failing test is not related to the changes, it fails the same way on ruby-head for longer time

**Comment by mpapis** [comment]
tests are passing, the code is rebased, anything else I should do?

**Comment by mpapis** [comment]
still waiting for the review

**Comment by mpapis** [comment]
still waiting for the review

**Comment by mpapis** [comment]
still waiting for the review

**Comment by mpapis** [comment]
still waiting for the review

**Comment by jcouball** [comment]
I am closing this PR to have a broader discussion about how `git config` should work in this gem in the next major release in #656.

**Pull request closed without merging**
