### PR TITLE
Allow creating new config entries

### PR DESCRIPTION
**Pull request by mpapis**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description

[Git 2.1.2 introduced setting values even if they did not previously exist.](https://github.com/git/git/blob/master/Documentation/RelNotes/2.1.2.txt#L16-L17)
The git-ruby library [keeps compatibility](https://github.com/ruby-git/ruby-git/blob/master/lib/git.rb#L25) with Git [1.6](https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L887), this fixes the
problem of older versions not being able to create new values.

#### Other options

- bump the minimal required git version to `2.1.2`

### CODE REVIEW

**Comment by mpapis** [comment]
tests are passing, the code is rebased, anything else I should do?

**Comment by mpapis** [comment]
still waiting for the review

**Comment by mpapis** [comment]
still waiting for the review

**Comment by mpapis** [comment]
still waiting for the review

**Comment by mpapis** [comment]
still waiting for the review

**Comment by jcouball** [comment]
I suspect that requiring 2.1.2 as the minimum git version might be burdensome to users.  According to [this page](https://en.wikipedia.org/wiki/Git), 2.1.2 was released in 2017.  I am interested in hearing what others think.

Looks like the implementation is to try the `git config` command without the `--add` switch first and then try using the `--add` switch if that fails.  While it works, it seems a bit sloppy since the initial command could have failed for other reasons.  That said, I can offer no better alternative at the moment.

Some things to consider as we evolve ruby-git further:
* Maybe the library should discover what version of git is being used and act more purposefully on what features are supported by the git client and which are not.
* It would be nice to be able to test with multiple versions of git so ruby-git's interaction with each version can be validated.

**Comment by jcouball** [comment]
Have you thought about adding a test for the situation covered by the change?  Is it possible with the existing state of the testing framework?

**Comment by mpapis** [comment]
I think it was to hard, the two other PR's from this time got tests (#399, #400), I'm moved already to other company, keeping the PR's alive as a courtesy to other OSS users.

**Comment by jcouball** [comment]
I am closing this PR to have a broader discussion about how `git config` should work in this gem in the next major release in #656.

**Pull request closed without merging**
