### PR TITLE
Add option to push all branches to a remote repo at one time

### PR DESCRIPTION
**Pull request by interhive**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description
Add the ability to push all local branches to a specific remote repository.

```ruby
# $ git push --all origin
git.push('origin', all: true)
```

### CODE REVIEW

**Comment by interhive** [comment]
I apologize for the misfire due to the erroneous DCO in my previous pull request.

**Comment by jcouball** [comment]
@interhive Thank you for your contribution!

There have been a few changes ahead of this one. Please rebase with master and push again and then I will run tests and merge to master.

❄️ Happy Holidays ❄️

**Comment by interhive** [comment]
Good morning, @jcouball 

I rebased with the master branch using GitHub's rebase feature. Let me know if you need anything else for this one!

Thanks and have a great holiday

**Review by jcouball — APPROVED** [review]
Looks great. Thank you for the contribution.

**Comment by jcouball** [comment]
I’ll publish a new version of the git gem in the next couple of days.

**Pull request merged**
