### PR TITLE
Support the commit --no-gpg-sign flag

### PR DESCRIPTION
**Pull request by bradleybuda**
### Description

Add the ability to send the `--no-gpg-sign` option to git. This is the default behavior in a "vanilla" git install, but if gpg signing is configured elsewhere (i.e. in `~/.gitconfig`) then you can use this option to override and disable it for a particular commit.

Triggered by `gpg_sign: false` - see test and README updates.

### CODE REVIEW

**Comment by jcouball** [comment]
@bradleybuda I like this PR, but I request the following change:

Instead of passing `gpg_sign` as false, I think it would be more consistent with the rest of the API to pass `no_gpg_sign`. You can see examples of this for the following:
* `git commit --no-verify`
* `git merge --no-commit`
* `git merge --no-ff`
* `git revert --no-edit`

The design of the API mimics what you would pass on the command line. Like it or not, that is the design we have today.

**Comment by jcouball** [comment]
I have fixed the Ruby 2.7 windows-latest build in #591

**Comment by bradleybuda** [comment]
Thanks for the comment @jcouball, updated the patch. I hadn't noticed that there were some other `--no-`-prefixed flags already in the code so agree that this should be consistent.

**Review by jcouball — APPROVED** [review]
Looks great! Thanks for the thorough tests!

**Pull request merged**
