### PR TITLE
#531 add API to get default branch

### PR DESCRIPTION
**Pull request by CAMOBAP**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [ ] Ensure that your contributions contain documentation if applicable.

### Description

#531 solution based on https://stackoverflow.com/a/44750379/902217

Open questions:
 - by default `origin` is used for remote, maybe there is a better alternative

### CODE REVIEW

**Comment by jcouball** [comment]
@CAMOBAP thank you for the PR. 

The default branch of the remote seems like it should be a property of a [Remote object](https://github.com/ruby-git/ruby-git/blob/master/lib/git/remote.rb).

If it were, I would like to get the remote's default branch by doing this:
`Git.open(working_dir).remote(remote_name).default_branch`

or:
`Git.open(working_dir).current_branch.remote.default_branch`

or (as a bonus) without having to have a local repository:
`Git.remote_default_branch(repository)`

What do you think of this design?

**Comment by CAMOBAP** [comment]
@jcouball sounds reasonable to me

**Comment by baweaver** [comment]
Very useful feature indeed, was going to mention the `taint` error for YARDoc but it looks like @jcouball was a few steps ahead there:

https://github.com/lsegal/yard/commit/7dca12cc53532ad1308113b2b09d51815897851f

**Comment by jcouball** [comment]
@CAMOBAP `Git.remote_default_branch(repository)` isn't implemented as I had intended. Pardon if I wasn't clear before. My intention was that you would give it a repository (like `Git.clone`) however:

```ruby
$ irb -I lib
2.7.5 :001 > require 'git'
 => true 
2.7.5 :002 > Git.remote_default_branch('https://github.com/ruby-git/ruby-git')
Traceback (most recent call last):
        1: from /Users/couballj/SynologyDrive/Documents/Projects/ruby-git-clean/https:/github.com/ruby-git/ruby-git
ArgumentError (path does not exist)
2.7.5 :003 > 
```

I have this implemented with tests, so if you remove Git.remote_default_branch and it's test from this PR, I accept it and then  follow with a separate PR for that.

```ruby
2.7.5 :002 > Git.remote_default_branch('https://github.com/ruby-git/ruby-git')
 => "master" 
2.7.5 :003 > Git.remote_default_branch('https://github.com/rspec/rspec-core')
 => "main" 
```

Also, it seems like `Lib#branch_default` should be named `Lib#default_branch`... if you agree, can you rename it?

**Comment by jcouball** [comment]
@CAMOBAP and @baweaver what do you think about #571 as a replacement for this PR's implementation of `Git.remote_default_branch`?

**Comment by CAMOBAP** [comment]
> @CAMOBAP and @baweaver what do you think about #571 as a replacement for this PR's implementation of `Git.remote_default_branch`?

To me #571 looks more elegant, so I'm totally ok if my PR will be rejected in favor of #571

**Comment by jcouball** [comment]
Closing this PR in favor of #571

**Pull request closed without merging**
