### PR TITLE
Basic Rebase

### PR DESCRIPTION
**Pull request by gmatheu**
Added **rebase** command on branch, base and lib.
Currently, if it can not automatic rebase, it aborts and resets to previous status.
Probable soon, I'll need to add more _interactive_ behaviour

If needed, I can write some documentation.

### CODE REVIEW

**Comment by victorgama** [comment]
@schacon Any prevision on getting this merged?

**Comment by Elexy** [comment]
would indeed be nice to have this

**Comment by lucywyman** [comment]
+1 on merging

**Comment by lucywyman** [comment]
For future folks who run into this, I ended up forking the project and doing the following:
```
git cherry-pick eee574a35e544cf1c8060f432c2d87a775d1f0c1
git cherry-pick -X theirs f68de47254fc4cacbc5b6045118e64f69203aaeb
git push origin master
```
Then in my gemfile I have:
```
gem 'ruby-git', :git => 'git://github.com/lucywyman/ruby-git'
```

Note that this makes it *difficult* to update this gem -- it basically assumes that this gem is never going to update. I don't know if that's true or not, but proceed with caution! You'll want to blow away your gem and redo the above steps if this gem does update.

**Comment by zedtux** [comment]
Please remove this stupid bot, we need this PR !

**Comment by zedtux** [comment]
@rvodden could you please merge this PR please ?

**Pull request closed without merging**
