### PR TITLE
Add `cherry` support to Git::Log

### PR DESCRIPTION
**Pull request by peterkovacs**

### CODE REVIEW

**Comment by perlun** [comment]
@peterkovacs Sorry for the lack of feedback on this one. Do you have a chance to rebase it on top off the latest `master` version?

**Comment by peterkovacs** [comment]
@perlun No problem. I've rebased and gotten the tests passing.

**Comment by jcouball** [comment]
Apologies, it looks like this PR has been sitting for a while.  If you want to get it merged, please fix the merge conflicts.  I took a look at them and it wasn’t obvious how to fix.

**Comment by peterkovacs** [comment]
Hi @jcouball, no worries. I have rebased the PR onto the latest master. Let me know if there's anything else you need.

**Comment by jcouball** [comment]
@peterkovacs sorry to have to come back to you one more time but your commit was missing the DCO sign-off so I merged a few other PRs ahead of this one.

Since I have made several merge commits that I don't want in the commit history, I think you should (1) roll your branch back to your Nov 22nd commit `8382b2b`, (2) rebase that with the current master, (3) include the DCO sign-off with the resulting commit, and (4) force push the result.

If there is a better/easier way to clean up the commits, I am open to suggestions.

If you can do this in the next day or so, I'll hold off on any other changes to master so you won't be asked to rebase again.

**Comment by jcouball** [comment]
@peterkovacs Sorry again for the bother. I'd love to land this PR for the next release but need your DCO sign off.

**Comment by peterkovacs** [comment]
@jcouball I _think_ i've done what you're looking for, please let me know if I screwed something up. Thank you!

**Review by jcouball — APPROVED** [review]
Thanks, @peterkovacs, the PR looks good.  Thank you!

**Pull request merged**
