### PR TITLE
Support type "commit" in output of "git ls-tree"

### PR DESCRIPTION
**Pull request by guillaumeaubert**
I got this error while analyzing my dot-files repo:

```
/home/guillaume/.rvm/gems/ruby-2.2.1/gems/git-1.3.0/lib/git/lib.rb:278:in `block in ls_tree': undefined method `[]=' for nil:NilClass (NoMethodError)
        from /home/guillaume/.rvm/gems/ruby-2.2.1/gems/git-1.3.0/lib/git/lib.rb:275:in `each'
        from /home/guillaume/.rvm/gems/ruby-2.2.1/gems/git-1.3.0/lib/git/lib.rb:275:in `ls_tree'
        from /home/guillaume/.rvm/gems/ruby-2.2.1/gems/git-1.3.0/lib/git/base.rb:526:in `ls_tree'
        from /home/guillaume/git-commits-analyzer/lib/git-commits-analyzer.rb:127:in `block in parse_repo'
        from /home/guillaume/.rvm/gems/ruby-2.2.1/gems/git-1.3.0/lib/git/log.rb:85:in `each'
        from /home/guillaume/.rvm/gems/ruby-2.2.1/gems/git-1.3.0/lib/git/log.rb:85:in `each'
        from /home/guillaume/git-commits-analyzer/lib/git-commits-analyzer.rb:119:in `parse_repo'
        from ./bin/analyze_commits:38:in `block in <main>'
        from ./bin/analyze_commits:36:in `each'
        from ./bin/analyze_commits:36:in `<main>'
```

I tracked it down to commits where I added a submodule - the "mounting point" of the submodule is recorded with a type of `"commit"` in git ls-tree:

```
$ git ls-tree -r 2760f9264653d2e315b13aeb4a3113c6b6df512a
100644 blob ffe9657f0791ddd2f5b448c88c1d129222a007cc    .gitignore
...
160000 commit fa7fde173fa77eb924fb65406b63169a8bf67657  tools/ps_mem
...
```

It causes this line in `lib/git/lib.rb` to fail because `"commit"` isn't a valid hash key for `type`:

```
data[type][filenm] = {:mode => mode, :sha => sha}
```

The proposed patch adds a `"commit"` key to the hash to make it a valid parseable type.

Another possibility would be to change the code to allow for any type in ls-tree. I'm happy to send you a separate patch for that if you would like.

Thank you for considering the pull request!

### CODE REVIEW

**Comment by valerioj** [comment]
i had the same error and i find this patch useful

**Comment by guillaumeaubert** [comment]
This is a trivial change and the checks are now passing. Any chance this could be merged? Thank you!

**Comment by guillaumeaubert** [comment]
👋

**Comment by guillaumeaubert** [comment]
👋

**Comment by tarcinil** [comment]
@guillaumeaubert 

Sorry for the length of time that has passed.  Please update your branch off of master and add tests that show ls-tree using commit to what you would expect. I would recommend creating a submodule fixture in tests/files so that we do not have any external dependencies.

I have pinned the PR so that stale bot will not re-label this.

Once you have completed, I will review.

**Comment by jcouball** [comment]
No test provided.  If you’d like to provide a test, I’ll take another look at this PR.

**Pull request closed without merging**
