### PR TITLE
Added mirror functionality for creating caches. 

### PR DESCRIPTION
**Pull request by antroy**
- Added --mirror flag to clone.
- Added remote-update for mirrors. 
- Added logging functionality into clone.

### CODE REVIEW

**Comment by guimaluf** [comment]
Why is this was abandoned ? Since 2014, this is a must have option to git clone lib!

**Comment by rvodden** [comment]
Hi @guimalut. The pull request lacks tests and had conflicts with master. If those two things are resolved we'll review and consider merging.

**Comment by guimaluf** [comment]
@rvodden is #167 enough?

**Comment by guimaluf** [comment]
I'll try to work on #167 
Thanks @rvodden

**Pull request closed without merging**
