### PR TITLE
Add YARD documentation to ruby-git

### PR DESCRIPTION
**Pull request by jcouball**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Ensure all commits include DCO sign-off.
- [ ] Ensure that your contributions pass unit testing.
- [ ] Ensure that your contributions contain documentation if applicable.

### Description

Create YARD documentation for ruby-git instead of rdoc. Make improvements to the documentation.

### CODE REVIEW

**Comment by jcouball** [comment]
@perlun CONTRIBUTING.md says that this project requires YARD documentation (even [before I rewrote it](https://github.com/ruby-git/ruby-git/blob/4aa6d1f0db40488e657b92be68696fdf5451109f/CONTRIBUTING.md)), but YARD was not really used at all.  RDoc was used inconsistently.

I was wondering if you thought it would be a good idea to add YARD documentation.

The work done so far shows what this would look like for most methods in the Git module like `Git.bare`, `Git.open`, `Git.clone`, `Git.init`.

In order to see this updated documentation, you will need to clone jcouball/ruby-git, and then run:

```
bundle install
bundle exec rake yard && open doc/index.html
```

Two areas to look at are the `Git` module and the `Files` page (accessed by clicking the 'Files' link in the top left under where it says 'Class List'.

**Comment by jcouball** [comment]
One interesting thing is that documenting the project has given me some good ideas for refactoring parts that are a little confusing.

**Comment by jcouball** [comment]
Today I learned that RubyGems automatically generates and hosts documentation for every gem published at rubydoc.info.  For instance: https://rubydoc.info/gems/git

**Comment by perlun** [comment]
@jcouball No strong feelings from my end as to whether to go with RDoc or YARD. I've used the latter previously myself though. In any case, we should definitely make it look good at https://rubydoc.info/gems/git

**Comment by jcouball** [comment]
I recreated this PR in #502

**Pull request closed without merging**
