### PR TITLE
Add Git push --set-upstream

### PR DESCRIPTION
**Pull request by olleolleolle**
Additional option was added to the `push` wrapper.

### CODE REVIEW

**Comment by LoicAG** [comment]
@perlun @tarcinil Could you please take a look at this PR, and possibly re-open / merge it?
It would be very useful to do the equivalent of:
```git push -u origin my_branch```

**Comment by tarcinil** [comment]
@LoicAG - Is it possible that you can add a test that would test to ensure that the upstream is set?

Lightly based on https://github.com/ruby-git/ruby-git/blob/master/tests/units/test_remotes.rb#L18

**Comment by jcouball** [comment]
Closing due to no test.  Happy to accept if a test is added.

**Comment by Bluelich** [comment]
Are there any update of this pr?

**Pull request closed without merging**
