### PR TITLE
feat: add --gpg-sign option on commits

### PR DESCRIPTION
**Pull request by othmane399**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description
This pull request add and option on `opts` hash to sign your commits using the default key that has been set in the config file

### CODE REVIEW

**Comment by othmane399** [comment]
@jcouball can you review this PR please ? it's about to add --gpg-sign flag on commit method

**Review by jcouball — COMMENTED** [review]
Thank you for submitting this PR.  I have a couple of requests:

1. I suggest that the key passed to `Git::Lib#commit` be 'gpg_sign' instead of just 'sign'.  I think it is important to keep this close to the git CLI.  I know this hasn't been done consistently, but I think it is a good idea.
2. I suggest, since we are here, allow passing an optional <keyid> as documented in [git-commit](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--Sltkeyidgt).  If the value of the key is `true` don't append the `"=#{keyid}"` to the argument.

Optional (if you don't do this, I can follow up with a separate PR for it):
* Add a test so that calling commit builds the command correctly.  I'd stub out `command` for this test.
* Add documentation to the README.md for this option.

**Comment by othmane399** [comment]
@jcouball thx for your review. I've done what you have recommended, can you recheck ?

**Review by jcouball — APPROVED** [review]
Thank you for making the requested changes.  I follow up with a PR to:

* Add a test so that calling commit builds the command correctly. I'd stub out command for this test.
* Add documentation to the README.md for this option.

I plan on building a new minor release within the next week to get this code into the gem.

**Pull request merged**
