### PR TITLE
Set default location on #ls_files to .

### PR DESCRIPTION
**Pull request by gudmundur**
If a `nil` is passed in to `#ls_files`, git will output a warning about empty strings in pathspec. At a future date, git will start failing on such arguments. See [here for more context](https://github.com/git/git/commit/d426430e6ec2a05bf0a4ee88c319dd6072908504).

### CODE REVIEW

**Comment by gudmundur** [comment]
The failing test is the Ruby 1.9.2 matrix, and there's [another PR to remove support for it](https://github.com/schacon/ruby-git/pull/318), as it's been deprecated for months.

**Comment by mmack** [comment]
This gets more urgent since git version 2.16.0 b/c it now throws a error: https://github.com/git/git/blob/master/Documentation/RelNotes/2.16.0.txt#L6

**Comment by schrepfler** [comment]
Is this being tackled?

**Comment by schrepfler** [comment]
This is still a problem.

**Comment by perlun** [comment]
I merged in `master` into this, but now the "changed files" says 0 files changed? Very odd. @gudmundur, thanks for the fix - if you or someone else could rebase this on top of the latest `master`, I'm happy to merge it in. Sorry for the huge delay of such a simple fix.

**Comment by perlun** [comment]
No feedback received. @gudmundur, if you'll do a rebase and ping me, I can reopen this. Closing for now.

**Comment by neomilium** [comment]
Fixed in #350

**Pull request closed without merging**
