### PR TITLE
Git::Lib#ls_tree ignore other types fix

### LINKED ISSUE #475: Git::Object::Tree#check_tree throws exception on a submodule, type 'commit'
### Subject of the issue

If I execute the following code on a workspace with a submodule:

```ruby
git = Git.open(@workspace_path, log: @logger)
gtree = git.gtree('HEAD')
head_sha = gtree.sha
subtrees = gtree.subtrees
```

... it fails with an undefined-method access on `Nil`.  

### Your environment

* ruby-git: 1.7.0

```console
> ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]
> git version
git version 2.21.1 (Apple Git-122.3)
  ```

### Steps to reproduce

1. clone a repo with a submodule reference
1. execute code in [subject](#subject-of-the-issue)

### Expected behaviour

`gtree.subtrees` should return a Hash of `String, Git::Object::Tree` entries.  (The existence of a submodule, ie a `commit` in `git ls-tree`, should not matter.)

### Actual behaviour

Git::Lib#ls_tree [has buckets for `blob`s and `tree`s][lib-rb-L275], but no buckets for other types, and no way to dodge around unknown types.  It finds a `commit` type object in the `git ls-tree` output, tries to [add the details of it to `data['commit'][filenm]`][lib-rb-L280], and breaks.

[lib-rb-L275]: https://github.com/ruby-git/ruby-git/blob/861eb71e1c266606eefacf7ebd4bee4f34bee5de/lib/git/lib.rb#L275
[lib-rb-L280]: https://github.com/ruby-git/ruby-git/blob/861eb71e1c266606eefacf7ebd4bee4f34bee5de/lib/git/lib.rb#L280

Log from the event:

```console
> bundle exec bin/do_my_thing -C .../project-with-submodule/directory-I-want
DEBUG: initializing for path .../project-with-submodule
INFO: Starting Git
INFO: git '--git-dir=.../project-with-submodule/.git' '--work-tree=.../project-with-submodule' '-c' 'color.ui=false' remote   2>&1
DEBUG: upstream
INFO: git '--git-dir=.../project-with-submodule/.git' '--work-tree=.../project-with-submodule' '-c' 'color.ui=false' config '--list'  2>&1
DEBUG: credential.helper=osxkeychain
user..... # redacted
color.ui=false
DEBUG: select origin from remotes: selecting the only remote found
INFO: git '--git-dir=.../project-with-submodule/.git' '--work-tree=.../project-with-submodule' '-c' 'color.ui=false' rev-parse 'HEAD'  2>&1
DEBUG: 5678e0c4bfc065bc4376d90d9c73610718d5bdac
INFO: git '--git-dir=.../project-with-submodule/.git' '--work-tree=.../project-with-submodule' '-c' 'color.ui=false' ls-tree 'HEAD'  2>&1
DEBUG: 100644 blob 866460808185230ccdd7550c52c26e416c4b9f3e	.gitignore
100644 blob 10afd8c81744c73ff197a6c929f674e31dc3afa4	.gitmodules
100644 blob e3e5603674013c56497287eac57307288ace6397	README.md
040000 tree 0399189c0abe35c236d28c7e5f9d4076fc083db2	another-directory
160000 commit b9ade9bfd3fbd436fb224e1340e8bf19196604c6	hated-submodule
040000 tree 1989bf2c80f7854e0257d5ab70f9b980c2fc9a1e	directory-I-want
100644 blob 408810cf89ad4a5c3008b707285f42284893a62e	that-file
100644 blob d8327e75a5cadb9fe42a7e1cb9b6d19e27320123	this-file
WARN: cannot access item 'deploy' from 'deploy' in git index; NoMethodError - undefined method `[]=' for nil:NilClass
ERROR: undefined method `[]=' for nil:NilClass
	.../my-project/vendor/bundle/ruby/2.6.0/gems/git-1.7.0/lib/git/lib.rb:280:in `block in ls_tree'
	.../my-project/vendor/bundle/ruby/2.6.0/gems/git-1.7.0/lib/git/lib.rb:277:in `each'
	.../my-project/vendor/bundle/ruby/2.6.0/gems/git-1.7.0/lib/git/lib.rb:277:in `ls_tree'
	.../my-project/vendor/bundle/ruby/2.6.0/gems/git-1.7.0/lib/git/object.rb:138:in `check_tree'
	.../my-project/vendor/bundle/ruby/2.6.0/gems/git-1.7.0/lib/git/object.rb:114:in `trees'
	bin/do_my_thing:68:in `block in config'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	.../.rbenv/versions/2.6.6/bin/bundle:23:in `load'
	.../.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by stujapa**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description

If `git ls-tree` includes items other than blobs and trees, Git::Lib.ls_tree
fails to either interpret or ignore the items.

Until first-class support is available, ignore types other than these two.  No
mechanism for logging or otherwise recording this action is available, so, the
unknown types are ignored silently.  (Debug logging elsewhere does include the
entire `git ls-tree` output.)

fixes #475

### CODE REVIEW

**Comment by stujapa** [comment]
Hi @jcouball – could you please review?  If I've missed something in CONTRIBUTING, please let me know.  Thanks!

**Comment by stujapa** [comment]
Hi @jcouball / @perlun / @tarcinil – could you please review?
Also, I'm sorry, travis-ci was triggered by this PR.  However, I don't see how to connect the [completed travis-ci run][travis-ci] with the PR so that status is reported properly.  Thanks!

[travis-ci]: https://travis-ci.org/github/ruby-git/ruby-git/builds/713149529

**Comment by stujapa** [comment]
Hi @rvodden / @perlun / @tarcinil – please, could you review this PR?
travis-ci completed tests successfully.  Please see https://travis-ci.org/github/ruby-git/ruby-git/builds/715390261 for details.  I'm not sure why this and the previous test runs are not automatically linked.
Thanks!

**Comment by jcouball** [comment]
Thank you, @stujapa for this PR.  Sorry I haven't gotten to it in a more timely manner.

In terms of functionality, I think this PR is fine.

Here is some general feedback about the tests that I wanted to run by you:
1. **What do you think about creating a test fixture specifically for this change?** Reusing the default test fixture (test/files/working/dot_git) as you can see breaks a bunch of tests that don't have anything to do with the change you are making. To me this is tech debt that is piling up with each change like this one. The next PR _might_ have to correct all the same tests plus the new ones introduced in this PR.
2. **What do you think about renaming your tests to indicate what is actually being tested?** When I read the tests, I am not sure what is being tested. Based on the point of the PR, I'd expect there to be a test named `test_ls_tree` (that already existed) which tests basic functionality and a new test called `test_ls_tree_ignores_unknown_types` (or similar) to test the situation where there is an unknown item type. I think this would be more intention revealing.

This project's documentation could stand for some improvement.  Right now, the most accessible and reliable documentation (other than the code) seems to be the README.md.  Can you add an example for `ls_tree` and add the caveat that only blobs and trees are listed and other item types (such as submodules) dropped?

**Comment by jcouball** [comment]
You can see an example of using a different fixture in `tests/units/test_diff_non_default_encoding.rb` for using the fixture `tests/files/encoding`

**Comment by jcouball** [comment]
I re-ran the build and the status was updated.  Not sure why it wasn't updating before.

**Comment by jcouball** [comment]
Thank you, @stujapa for this contribution.

I have fixed the issue in #643. Rather than ignoring commits returned by `ls-files`, that PR actually returns them with the other objects retuned by `ls-files`.

**Pull request closed without merging**
