### PR TITLE
Assume strings are utf8 by default and fallback on encoding if necessary

### PR DESCRIPTION
**Pull request by kamaradclimber**
Before this patch, we always assumed the string was ascii-8bit which
does not work correctly with real utf8 strings (french accented chars or
chineese chars).

This patch tries to use the string as utf8 and fallback if necessary to
the the ascii-8bit assumption if necessary.

This should help with #295 and might replace the need for #301.

Change-Id: Idac63fa10e5aefafa1eb99a6be4138cac5f90ea0

### CODE REVIEW

**Comment by kamaradclimber** [comment]
Sorry for the removal of ruby 1.9.2 without prior discussion. At the moment tests cannot pass (even in master) for ruby 1.9.2 (see my comment on my second commit).

**Comment by kamaradclimber** [comment]
@rvodden would you consider this PR if I fixed the conflicts?

**Comment by kamaradclimber** [comment]
@perlun I am willing to fix the conflicts if you are interested in the PR. let me know

**Comment by perlun** [comment]
@kamaradclimber I think #327 supersedes this. Could you try with the latest master and see if this assumption is right? If not, we can discuss it further - I'm open to changes that fixes bugs in the implementation.

**Comment by kamaradclimber** [comment]
thanks for the answer. I'll close the PR and test latest master

**Pull request closed without merging**
