### PR TITLE
Add Truffleruby-head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by gogainda** [comment]
@AndyObtiva pls review/merge

**Comment by jcouball** [comment]
@gogainda why are we adding Truffle Ruby to the test suite?  Is there something we think needs to be uniquely tested in Truffle Ruby?

**Comment by gogainda** [comment]
@jcouball we are tracking truffleruby's compatibility with other gems in this project https://github.com/eregon/truffleruby-gem-tracker , so once it's added in CI we can see the status of the gem

**Comment by jcouball** [comment]
@gogainda I am considering moving this build to GitHub Actions. TravisCI is limiting access to open source projects like ruby-git.

I am preparing a PR to accomplish this.

I was wondering if you have any feedback to this?

**Comment by gogainda** [comment]
sure, will recreate a PR once you moved to Github Actions

**Comment by jcouball** [comment]
@gogainda I added the Truffle Ruby build when implementing the GitHub Actions CI build in #498.

**Pull request closed without merging**
