### PR TITLE
Fix UTF-8 message errors

### PR DESCRIPTION
**Pull request by drakmail**
Without this fix I got questions instead chars:

"������������������ ������������"

### CODE REVIEW

**Comment by barakwei** [comment]
👍

**Comment by voxik** [comment]
This seems to be similar to #318

**Comment by voxik** [comment]
And #304

**Comment by voxik** [comment]
And #301

**Comment by perlun** [comment]
@voxik I think perhaps auto-closing _PRs_ is a bit too aggressive. Issues is one thing, but open PRs should perhaps be exempt from auto-closing; we don't have _that_ many PRs at the moment so I think manual action to go through them is better than auto-closing.

Thanks for letting me know.

**Comment by perlun** [comment]
@voxik I think perhaps auto-closing _PRs_ is a bit too aggressive. Issues is one thing, but open PRs should perhaps be exempt from auto-closing; we don't have _that_ many PRs at the moment so I think manual action to go through them is better than auto-closing.

Thanks for letting me know.

**Comment by drakmail** [comment]
Thank you for merge!

**Pull request merged**
