### PR TITLE
Add no verify for commit

### PR DESCRIPTION
**Pull request by AgoraSecurity**
In git commit, add:
       -n, --no-verify
           This option bypasses the pre-commit and commit-msg hooks. See also githooks(5).

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description
Add option to bypasses the pre-commit and commit-msg hooks

### CODE REVIEW

**Comment by AgoraSecurity** [comment]
@perlun and @tarcinil -- this PR is ready for review.

**Comment by AgoraSecurity** [comment]
@perlun and @tarcinil -- this PR is ready for review.

**Comment by jcouball** [comment]
This change looks good, but needs unit tests and documentation updates.

**Comment by AgoraSecurity** [comment]
@jcouball Sure, I'll work in unit tests and documentation updates.

By the way, if you could point me to files (example of desired updates, etc.) it will really help me.

Thanks!

**Comment by jcouball** [comment]
**Documentation**

Our CONTRIBUTING.md says that yard docs should be added / updated on all methods though I can see that hasn't been done consistently.

I would expect the yard doc for Lib::commit to be added.  A good example can be found for Lib::diff_as_hash:
https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L981-L985

I'd say that documenting this option in the README.md is optional.

**Unit Testing**

Unit tests can be found here:
[https://github.com/ruby-git/ruby-git/tree/master/tests/units](https://github.com/ruby-git/ruby-git/tree/master/tests/units)

and are run with the command:
`bundle exec rake test`

I don't see that tests already exist for `commit` which makes your job harder.  Feel free to take a look at other existing tests and see if you can figure it out.  I'll dig in deeper to give you more advice, but it will take me some time to get to that.

**Comment by jcouball** [comment]
**Documentation**

Our CONTRIBUTING.md says that yard docs should be added / updated on all methods though I can see that hasn't been done consistently.

I would expect the yard doc for Lib::commit to be added.  A good example can be found for Lib::diff_as_hash:
https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L981-L985

I'd say that documenting this option in the README.md is optional.

**Unit Testing**

**Comment by AgoraSecurity** [comment]
Closed in favor of https://github.com/ruby-git/ruby-git/pull/454

**Pull request closed without merging**
