### PR TITLE
fix broken link in a PR template

### PR DESCRIPTION
**Pull request by yuta1024**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description
This PR fixes the broken link to `CONTRIBUTING.md` in a PR template.

### CODE REVIEW

**Comment by jcouball** [comment]
Haha, was just about to open a PR for the same.  I appreciate that you beat me to it.

I think that, although the same, this would be more concise:

`[guidelines for contributing](CONTRIBUTING.md)`

If you are willing to make that change and then squash the commit, I'll immediately approve this PR.

**Comment by jcouball** [comment]
Further, I think you have to let the CI build run in order for ME to be able to merge this as the travis-ci build is a required check.  I don't have permission to override this check.

Can you please remove the [ci skip] message from the commit and PR?

**Comment by yuta1024** [comment]
Thank you for your quickly response!

**Comment by jcouball** [comment]
@yuta1024 it ends up that our fix did not work when viewed in an actual PR.

It worked when viewing `PULL_REQUEST_TEMPLATE.md` from Github, but not from within an actual PR which is relative to `https://guthub.com/ruby-git/ruby-git/pull/`

The only thing that works in both contexts is an absolute link:
`https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md`

See examples here:
https://github.com/ruby-git/ruby-git/pull/445

Do you want to do a new PR with the absolute URL or shall I?

**Comment by yuta1024** [comment]
@jcouball Oh... I didn't confirm that the link works fine when viewed in a PR.
OK, I will fix to absolute link and send PR as soon as possible.

**Comment by yuta1024** [comment]
I created PR #446 . Could you please confirm it?

**Pull request merged**
