### PR TITLE
Check if branch contains commit

### PR DESCRIPTION
**Pull request by kwstannard**
This allows the user to see if an arbitrary commit is contained within a
branch. For example you can check to see if a branch was merged into
master with `git.branch('master').contains?('feature')`. Or you can see
if your feature branch has the latest master commit with
  `git.branch('feature').contains?('master')`

### CODE REVIEW

**Comment by kwstannard** [comment]
I am no longer using ruby-git day to day. I wont update unless the maintainer is interested.

**Comment by rvodden** [comment]
@kwstannard if you could rebase it - I'll merge it in - it looks like a really helpful feature.

**Comment by kwstannard** [comment]
@rvodden updated, hope it helps.

**Comment by kwstannard** [comment]
@rvodden

**Comment by perlun** [comment]
@kwstannard Sorry for the delay. Could you rebase one more time? (hopefully the last time...) Thanks.

**Comment by kwstannard** [comment]
I am just going to close this. If you want it, I guess just open it and merge???

**Comment by kwstannard** [comment]
@perlun

**Comment by kwstannard** [comment]
Looks like you probably just need to restart that failed job

**Comment by tarcinil** [comment]
Closed and opened to trigger Travis.

**Pull request merged**
