### PR TITLE
Do not assume the default branch is 'master' in tests

### PR DESCRIPTION
**Pull request by liijunwei**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description

Fix test case by extracting `init.defaultBranch` into variable
https://github.com/ruby-git/ruby-git/issues/587

### CODE REVIEW

**Comment by jcouball** [comment]
This code does not work when `init.defaultBranch` is not set (see the failed CI builds for this PR).

In this case, you see the following:
```ruby
$ irb
2.7.6 :001 > `git config --get init.defaultBranch`
 => "" 
2.7.6 :002 > $?
 => #<Process::Status: pid 54561 exit 1> 
2.7.6 :003 > 
```

I think you could get away with adding this line:
```ruby
initial_branch = 'master' if initial_branch.empty?
```

See [the docs for `git init --initial-branch`](https://git-scm.com/docs/git-init#Documentation/git-init.txt---initial-branchltbranch-namegt) for more context.

**Comment by liijunwei** [comment]
yes, thanks for reminding me 🙏 

I reproduced by removing `  defaultBranch = main` in my `~/.gitconfig` and changed the test case as your suggestion
I also did some commit cleanup(cherry-pick and force pushed)

**Comment by liijunwei** [comment]
also suggest rename `test_git_init` to `test_git_init_with_default_init_default_branch`

**Review by jcouball — APPROVED** [review]
Looks great, @liijunwei! Thank you for the contribution.

**Pull request merged**
