### PR TITLE
Simplify git commands

### PR DESCRIPTION
**Pull request by hatkyinc2**
### Description
`git -C` to replace the confusing pair of `--git-dir` and `--work-tree`

### CODE REVIEW

**Comment by jcouball** [comment]
I think having both `--git-dir` and `--work-tree` options is necessary to cover the case where the `.git` directory isn't located within the work tree or isn't named `.git`.

It seems like we should have tests for that but I guess we don't since the tests passed with this change.

**Comment by hatkyinc2** [comment]
the `.git` being a file in place of a directory is exactly the reason I started down the rabbit hole, I believe it currently has bugs, for both submodules and worktrees, opening a Git and trying to checkout a new branch fails. Even if the submodules code is to be fixed it should be duplicated or moved to the initialize function.
I'm in too deep and I'm a bit lost for a few days already...

The two switches need to be amended differently for each case and I'm yet to fully get exactly how they work, couldn't find much documented to explain what they mean.
I also get into weird states where the change tree doesn't match the preped files or a .lock file missing issue...
So the `-C` is close to an actual change directory, which actually works in place of the two switches for all cases. `git` CLI just figures them alone and the rest of the stuff.. you may still override them even after a `-C` when they would be relative to that (assuming relative paths are used over full ones)

**Comment by hatkyinc2** [comment]
I'm happy to add tests for these, due they currently fail for other stuff...
If you want to depend this change merge on added tests for submodule and worktree, that's fine.

**Comment by hatkyinc2** [comment]
So this is a submodule test it fails for both master and here 😭 
https://github.com/ruby-git/ruby-git/pull/488

But my conclusions from it are:
* This code is probably not useful https://github.com/ruby-git/ruby-git/blob/master/lib/git/base.rb#L58-L65
* The separation of `--git-dir` and `--work-tree` over `-C` doesn't help currently

**Comment by hatkyinc2** [comment]
This is a test for worktree new branch checkout, same error as with the submodule
https://github.com/ruby-git/ruby-git/pull/489

**Comment by hatkyinc2** [comment]
I think at this point I need help.
Like I don't get it, if I do exactly as the test and the command listed on the terminal it works
But obviously this doesn't work.

It's probably something super silly, that's how it usually works :(

**Comment by jcouball** [comment]
@hatkyinc2 I was wondering if you could take a look at #490.  In addition to fixing a bug (how the default for `index` is calculated) it also adds a test for when `git-dir` is in a non-standard place relative to `work-tree`.  This test should fail with the change you are proposing in this PR.

**Comment by jcouball** [comment]
Closing this for the reasons stated in the comments above.  It comes down to the matter that sometimes the `.git` file/directory is not within the working copy.

**Pull request closed without merging**
