### PR TITLE
Removed blank (1 char change) after method name to fix this warning:

### PR DESCRIPTION
**Pull request by jasnow**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Ensure all commits include DCO sign-off.
- [X] Ensure that your contributions pass unit testing.
- [X] Ensure that your contributions contain documentation if applicable.

### Description
Removed blank (1 char change) after method name to fix this warning:
```
Users/USER/rvm/gems/ruby-2.7.0-rc1@ruby2.7-no-rails/gems/git-1.5.0/lib/git/branch.rb:40:
warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
```

### CODE REVIEW

**Comment by AgoraSecurity** [comment]
Looks good

**Comment by jasnow** [comment]
@robertodecurnex - Can you assign a "reviewer with write access" to review this 1 char change since a review is required before merging? Thanks.

**Comment by jcouball** [comment]
@jasnow can you please rebase with master?  If you do that, I will get this change merged.

**Comment by jasnow** [comment]
Bye

**Comment by jcouball** [comment]
Sorry to see you go @jasnow.  I created #439 for this fix.

**Pull request closed without merging**
